server:
  port: 8000
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/actingdriver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: ActingDriver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 30MB

file:
  dummyProfile: dummyProfile.png
  dummyCar: dummyCar.png
  dummyImage-dir: ./src/main/resources/uploads
  actor-profile-upload-dir: ./src/main/resources/uploads/actors/profiles-images
  client-profile-upload-dir: ./src/main/resources/uploads/clients/profile-images
  car-upload-dir: ./src/main/resources/uploads/cars/car-images


