server:
  port: 8000
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/actingdriver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: ActingDriver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 30MB

file:
  dummyProfile: dummyProfile.png
  upload-dir: ./src/main/resources/upload


